### ISSUE TITLE
Android  7.0 is not working

### ISSUE THREAD

**Issue by petrovichtim** [Abhi347/NoobCameraFlash#1]
Good day!
I got Nexus5x  with android Nougat. 
Method NoobCameraManager.getInstance().turnOnFlash(); is not working.
Also library com.noob.lumberjack add permissions to manifest what is not needings in my project.
Can you make to disble it?

**Comment by Abhi347** [comment]
Thanks for reporting the issue. Unfortunately, I don't have any device which is running on Nougat yet. I'll try to fix it as soon as I can. In the meantime, can you provide any crash log or Logcat output which may help me to debug it?
WRT permissions, I guess I am asking for Camera Permission only which is actually a requirement for the library. Please read here for more details - http://stackoverflow.com/questions/36259930/which-permissions-are-required-for-flashlight

**Comment by petrovichtim** [comment]
I mean this one
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`
wich adds  package="com.noob.lumberjack" to result manifest file.
I dont need this permissions in my app.

**Comment by Abhi347** [comment]
Currently, it's not possible to remove the permission without removing LumberJack from the project (Which will be like killing an extra feature). 
However, you're always free to edit the source code yourself (under the licensing terms, of course). You'll need to remove LumberJack as a dependency or if you just want to keep it's Locat logging feature then you can edit the source code of LumberJack too (Which is also open sourced ) and remove the permissions.
PS: Please post one issue in one thread.

**Comment by Abhi347** [comment]
Please check #2 
The permissions are removed from the LumberJack as well as from NoobCameraFlash too.
I am yet to check the library in Android 7.0, so keeping this issue open.

**Comment by Abhi347** [comment]
The latest release 0.1.0 should fix this issue. Closing this issue as the build is now working in Marshmallow (Still can't check in Nougat). Please reopen if it doesn't work.
