### ISSUE TITLE
How to init singleton from service?

### ISSUE THREAD

**Issue by petrovichtim** [Abhi347/NoobCameraFlash#3]
how to run the module from the service?

**Comment by Abhi347** [comment]
In the current version, you can not, as the activity object is required to initialize the Singleton which initializes the various OS-specific utilities. The activity context is required mainly to check runtime permissions.
Thus it may be possible to completely eliminate the requirement of the Activity context if we can remove the permission check from the utilities. I'll try to fix it in the next version probably within a couple of weeks. In the mean time feel free to modify the source code and remove the dependency yourself.

**Comment by Abhi347** [comment]
Removed permissions and changed Activity object to context object in the version 0.2.0. Please check that.
